services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  identity-service:
    image: semokati/identity-service:latest
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=AspIdUsers;
    depends_on:
      - postgres
  auction-service:
    image: semokati/auction-service:latest
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
    ports:
      - 7001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__Default=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions;
      - IdentityServiceUrl=http://identity-service
    depends_on: 
      - postgres
      - rabbitmq
  search-service:
    image: semokati/search-service:latest
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    ports:
      - 7002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-service
    depends_on:
      - mongodb
      - rabbitmq
      - auction-service
  gateway-service:
    image: semokati/gateway-service:latest
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
#volumes:
#  pgdata:
#  mongodata:

#  auctionservice:
#    image: auctionservice
#    build:
#      context: .
#      dockerfile: AuctionService/Dockerfile

